// Generated by CoffeeScript 1.6.3
var hub;

hub = $({});

$.getJSON("data.json", function(data) {
  var e;
  window.data = data;
  e = $.Event("jsonComplete");
  e.jsonData = data;
  return hub.trigger(e);
});

hub.on("jsonComplete", function(event) {
  var data;
  console.log("READY...");
  data = event.jsonData;
  return window.collection = new Barebones.Collection(data);
});
